# Generated by Django 6.1.1 on 2026-09-06 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categorynode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tree_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.categorynode'),
        ),
    ]
