# Generated by Django 6.1.1 on 2026-09-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tree_category',
            new_name='category',
        ),
    ]
